export const ClientDatas = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    to: "05",
    ts: 50,
    status: "Active",
    activeProject: "none",
    date: "24.Jan.2021",
  },
  {
    id: 2,
    name: "John Smith",
    email: "john.doe@example.com",
    to: "08",
    ts: 40,
    status: "Active",
    activeProject: "Project Hellocer Front end dev...",
    date: "24.Jan.2021",
  },
  {
    id: 3,
    name: "John Doe",
    email: "john.doe@example.com",
    to: "15",
    ts: 120,
    status: "Inactive",
    activeProject: "Project Hellocer Front end dev...",
    date: "24.Jan.2021",
  },
  {
    id: 4,
    name: "Seun David",
    email: "seun@example.com",
    to: "22",
    ts: 100,
    status: "Inactive",
    activeProject: "Project Hellocer Front end dev...",
    date: "10.Jul.2021",
  },
  {
    id: 5,
    name: "Frank Doe",
    email: "john.doe@example.com",
    to: "20",
    ts: 210,
    status: "Active",
    activeProject: "Project Hellocer Front end dev...",
    date: "24.Feb.2021",
  },
];
