import slide4 from "/Images/slide4.png";
import slide9 from "/Images/slide9.png";
import slide10 from "/Images/slide10.png";
import slide11 from "/Images/slide11.png";
import slide12 from "/Images/slide12.png";
import slide13 from "/Images/slide13.png";
import slide14 from "/Images/slide14.png";
import slide15 from "/Images/slide15.png";
import slide16 from "/Images/slide16.png";
import slide17 from "/Images/slide17.png";
import star from "/Images/star.png";

export const data = {
  image1: slide4,
};

export const text_data = [
  {
    id: 1,
    display: slide10,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 2,
    display: slide13,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 3,
    display: slide14,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 4,
    display: slide15,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 5,
    display: slide16,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 6,
    display: slide9,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 7,
    display: slide11,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 8,
    display: slide12,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 9,
    display: slide14,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 10,
    display: slide15,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 11,
    display: slide15,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 12,
    display: slide16,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 13,
    display: slide11,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 14,
    display: slide12,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 15,
    display: slide14,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 16,
    display: slide15,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 17,
    display: slide15,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 18,
    display: slide16,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 19,
    display: slide10,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 20,
    display: slide13,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 21,
    display: slide14,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 22,
    display: slide15,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 23,
    display: slide16,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 24,
    display: slide9,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 25,
    display: slide15,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 26,
    display: slide16,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 27,
    display: slide13,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 28,
    display: slide14,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 29,
    display: slide9,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 30,
    display: slide11,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 31,
    display: slide16,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 32,
    display: slide10,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },
  {
    id: 33,
    display: slide16,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 34,
    display: slide13,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 35,
    display: slide14,
    image: slide17,
    name: "Brandly James",
    work: "I will design a functional logo",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },

  {
    id: 36,
    display: slide9,
    image: slide17,
    name: "Brandly James",
    work: "I will design amazing website with good UX design",
    star,
    star_text: "4.8",
    star_number: "(255)",
    price: "From $120",
  },
];
